[package]
name = "modelctl"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
publish = false

[lib]
name = "modelctl"
path = "src/lib.rs"

[[bin]]
name = "modelctl"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
clap_complete.workspace = true
modeld-core = { package = "syntrop-modeld-core", version = "0.2.0", path = "../modeld-core" }
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
