# Type Name   ID GECOS                                          Home Directory Shell
u     modeld -  "Syntropd Model Asset Store and Broker"       /var/lib/models /usr/sbin/nologin
m     modeld render
